// src/lib/openings-sample-data.ts
// Placeholder dataset for local development of the Opening Explorer.
// Swap for a real database / generated ECO dataset later — the search
// component only depends on the OpeningSummary shape, not this file.

import type { OpeningSummary } from "@/types/opening";

export const SAMPLE_OPENINGS: OpeningSummary[] = [
  {
    id: "italian-game",
    name: "Italian Game",
    eco: "C50",
    moves: "e4 e5 Nf3 Nc6 Bc4",
    category: "King's Pawn",
    difficulty: "beginner",
    popularity: 92,
    winRateWhite: 52,
    drawRate: 30,
    trending: true,
  },
  {
    id: "ruy-lopez",
    name: "Ruy Lopez",
    eco: "C60",
    moves: "e4 e5 Nf3 Nc6 Bb5",
    category: "King's Pawn",
    difficulty: "advanced",
    popularity: 88,
    winRateWhite: 54,
    drawRate: 34,
  },
  {
    id: "sicilian-najdorf",
    name: "Sicilian Defense: Najdorf Variation",
    eco: "B90",
    moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",
    category: "Sicilian",
    difficulty: "advanced",
    popularity: 95,
    winRateWhite: 51,
    drawRate: 28,
    trending: true,
  },
  {
    id: "sicilian-dragon",
    name: "Sicilian Defense: Dragon Variation",
    eco: "B70",
    moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6",
    category: "Sicilian",
    difficulty: "advanced",
    popularity: 74,
    winRateWhite: 50,
    drawRate: 27,
  },
  {
    id: "french-defense",
    name: "French Defense",
    eco: "C00",
    moves: "e4 e6",
    category: "French",
    difficulty: "intermediate",
    popularity: 68,
    winRateWhite: 53,
    drawRate: 31,
  },
  {
    id: "caro-kann",
    name: "Caro-Kann Defense",
    eco: "B10",
    moves: "e4 c6",
    category: "Caro Kann",
    difficulty: "intermediate",
    popularity: 65,
    winRateWhite: 52,
    drawRate: 33,
  },
  {
    id: "queens-gambit",
    name: "Queen's Gambit",
    eco: "D06",
    moves: "d4 d5 c4",
    category: "Queen's Pawn",
    difficulty: "intermediate",
    popularity: 90,
    winRateWhite: 55,
    drawRate: 35,
    trending: true,
  },
  {
    id: "kings-indian",
    name: "King's Indian Defense",
    eco: "E60",
    moves: "d4 Nf6 c4 g6",
    category: "Indian",
    difficulty: "advanced",
    popularity: 79,
    winRateWhite: 51,
    drawRate: 26,
  },
  {
    id: "nimzo-indian",
    name: "Nimzo-Indian Defense",
    eco: "E20",
    moves: "d4 Nf6 c4 e6 Nc3 Bb4",
    category: "Indian",
    difficulty: "advanced",
    popularity: 81,
    winRateWhite: 50,
    drawRate: 37,
  },
  {
    id: "english-opening",
    name: "English Opening",
    eco: "A10",
    moves: "c4",
    category: "English",
    difficulty: "intermediate",
    popularity: 71,
    winRateWhite: 53,
    drawRate: 33,
  },
  {
    id: "kings-gambit",
    name: "King's Gambit",
    eco: "C30",
    moves: "e4 e5 f4",
    category: "Gambits",
    difficulty: "advanced",
    popularity: 40,
    winRateWhite: 49,
    drawRate: 24,
  },
  {
    id: "scotch-game",
    name: "Scotch Game",
    eco: "C45",
    moves: "e4 e5 Nf3 Nc6 d4",
    category: "King's Pawn",
    difficulty: "beginner",
    popularity: 60,
    winRateWhite: 53,
    drawRate: 30,
  },
];
